name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential lld

      - name: Build with make
        run: make

      - name: Download RecompModTool
        run: |
          wget -O RecompModTool https://github.com/N64Recomp/N64Recomp/releases/download/mod-tool-release/RecompModTool
          chmod +x RecompModTool

      - name: Run RecompModTool
        run: ./RecompModTool mod.toml build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nrm-artifact
          path: build/*.nrm
